Add scripts from dotfiles.

diff --git a/android-setup b/android-setup
--- a/android-setup
+++ b/android-setup
@@ -1,2 +1,15 @@
-# Install 64 bit libraries
-sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386 lib32z1 libbz2-1.0:i386
+#!/bin/bash
+if [ $(uname) = "Linux" ]; then
+  URL=https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
+elif [ $(uname) = "Darwin" ]; then
+  URL=https://dl.google.com/android/repository/sdk-tools-darwin-3859397.zip
+fi
+
+wget -0 sdk-tools.zip $URL
+
+unzip sdk-tools -d ~/DevTools/android/sdk
+if [ $? == 0 ]; then
+  echo "Android SDK Tools installed."
+else
+  echo "Android SDK Tools installation failed."
+fi
